// <auto-generated />
namespace Delphinus_Yachts.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class OneBookingToZeroContracts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OneBookingToZeroContracts));
        
        string IMigrationMetadata.Id
        {
            get { return "202001172227039_OneBookingToZeroContracts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
